### ISSUE TITLE
Potential Security Issue

### ISSUE THREAD

**Issue by supriza** [ljharb/js-traverse#1]
Hi @benatkin @ljharb @karlbohlmark @grncdr @harthur ,
My name is Raul and I'm a security researcher at Snyk. There might be a security issue in your package.
Where can I contact you in private to discuss things?
Thanks!

**Comment by ljharb** [comment]
Hi @supriza; the security policy at https://github.com/ljharb/js-traverse/security/policy should cover this :-)

**Comment by supriza** [comment]
Thanks @ljharb, I missed that!

**Comment by benatkin** [comment]
such willingness to waste my time `_._`

more inclined to go w/ socket.dev now =)

**Comment by ljharb** [comment]
@benatkin i'm not sure what you mean?

**Comment by benatkin** [comment]
@ljharb I mean a security researcher from Snyk mentioned my name in a list and didn't check for a security policy

not a big deal I guess :)

**Comment by ljharb** [comment]
Going to close this for now.
